$ENV{'TEXINPUTS'}=':' if length $ENV{'TEXINPUTS'} == 0;
$ENV{'TEXINPUTS'}='./../../support//:' . $ENV{'TEXINPUTS'}; 
$ENV{'TEXINPUTS'}='./../../../../support//:' . $ENV{'TEXINPUTS'}; 
$ENV{'OSFONTDIR'}="./../../fonts";
$pdflatex = "lualatex %O %S";

# vim:ft=perl
